
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftSumaRestarightMultiDiviDivi Igual Multi Numero Resta Sumaexpresion : expresion Suma terminoexpresion : expresion Resta terminoexpresion : terminotermino : termino Multi factortermino : termino Divi factortermino : factorfactor : Numeroexpresion : error'
    
_lr_action_items = {'error':([0,],[3,]),'Numero':([0,6,7,8,9,],[5,5,5,5,5,]),'$end':([1,2,3,4,5,10,11,12,13,],[0,-3,-8,-6,-7,-1,-2,-4,-5,]),'Suma':([1,2,3,4,5,10,11,12,13,],[6,-3,-8,-6,-7,-1,-2,-4,-5,]),'Resta':([1,2,3,4,5,10,11,12,13,],[7,-3,-8,-6,-7,-1,-2,-4,-5,]),'Multi':([2,4,5,10,11,12,13,],[8,-6,-7,8,8,-4,-5,]),'Divi':([2,4,5,10,11,12,13,],[9,-6,-7,9,9,-4,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expresion':([0,],[1,]),'termino':([0,6,7,],[2,10,11,]),'factor':([0,6,7,8,9,],[4,4,4,12,13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expresion","S'",1,None,None,None),
  ('expresion -> expresion Suma termino','expresion',3,'p_expresion_suma','anal2.py',44),
  ('expresion -> expresion Resta termino','expresion',3,'p_expresion_resta','anal2.py',48),
  ('expresion -> termino','expresion',1,'p_expresion_termino','anal2.py',52),
  ('termino -> termino Multi factor','termino',3,'p_termino_multi','anal2.py',56),
  ('termino -> termino Divi factor','termino',3,'p_termino_divi','anal2.py',60),
  ('termino -> factor','termino',1,'p_termino_factor','anal2.py',64),
  ('factor -> Numero','factor',1,'p_factor_numero','anal2.py',68),
  ('expresion -> error','expresion',1,'p_expresion_error','anal2.py',72),
]
